apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: cs-quiz-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi