apiVersion: v1
kind: Secret
metadata:
  name: cs-db-secret
  namespace: cs-quiz-app
type: Opaque
data:
  db-password: MTIzNDVh
  gemini-api-key: QUl6YVN5QmNoUG5jRjhpYTBDVldtM2ctb1lRTi1NQUw4OG40NTZj
  flask-secret-key: bXktcXVpei1wcm9qZWN0